sudo: required

language: php

dist: trusty

php:
  - '7.0'
  - '7.1'

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - cp .env.travis .env
  - cp .env.dusk.travis .env.dusk.local
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - php artisan dusk

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_dusk;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_testing;'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON boilerplate_dusk.* to travis@'%';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON boilerplate_testing.* to travis@'%';"

addons:
  mariadb: '10.1'
  artifacts:
    s3_region: 'ap-south-1'
    paths:
      - $(ls ./tests/Browser/screenshots/*.png | tr "\n" ":")
      - $(ls ./storage/logs/*.log | tr "\n" ":")
