language: php

php:
    - '7.0'
    - '7.1'

before_script:
    - composer self-update
    - composer install --dev --prefer-source --no-interaction

scripts:
    - vendor/bin/phpunit

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_testing;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_dusk;'
    - mysql -e "GRANT ALL PRIVILEGES ON boilerplate_testing.* to forge@'localhost' IDENTIFIED BY 'secret';"
    - mysql -e "GRANT ALL PRIVILEGES ON boilerplate_dusk.* to forge@'localhost' IDENTIFIED BY 'secret';"

addons:
    mariadb: '10.1'

env:
    - DB_USERNAME=forge
    - DB_PASSWORD=secret
