sudo: required

language: php

dist: trusty

php:
    - '7.0'
    - '7.1'

before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - php artisan key:generate
    - cp .env.travis .env
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - ./vendor/laravel/dusk/bin/chromedriver-linux &
    - php artisan serve &

script:
    - vendor/bin/phpunit
    - php artisan dusk

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_testing;'
    - mysql -e 'CREATE DATABASE IF NOT EXISTS boilerplate_dusk;'

addons:
    mariadb: '10.1'
